"""ajustar cestas

Revision ID: 1b257d14250f
Revises: ea3632575eba
Create Date: 2025-09-07 13:31:51.339439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b257d14250f'
down_revision: Union[str, Sequence[str], None] = 'ea3632575eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_cesta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categoria_cesta_id'), 'categoria_cesta', ['id'], unique=False)
    op.add_column('cesta', sa.Column('categoria_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cesta', 'categoria_cesta', ['categoria_id'], ['id'])
    op.drop_column('cesta', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cesta', sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cesta', type_='foreignkey')
    op.drop_column('cesta', 'categoria_id')
    op.drop_index(op.f('ix_categoria_cesta_id'), table_name='categoria_cesta')
    op.drop_table('categoria_cesta')
    # ### end Alembic commands ###
